#!/bin/bash
#PBS -S /bin/bash
#PBS -V
#PBS -W group_list=cosmo
#PBS -q standard
#PBS -l select=1:ncpus=1:mem=6GB
#PBS -l place=free:shared
#PBS -l walltime=100:00:00
#PBS -N KL_W1st_30_cov
#PBS -e /home/u17/jiachuanxu/output/
#PBS -o /home/u17/jiachuanxu/output/

module load gsl/2/2.1

cd $PBS_O_WORKDIR
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 55843
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 56307
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 71188
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 71652
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 71653
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 72117
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 72118
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 72582
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 72583
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73047
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73048
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73512
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73513
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73977
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 73978
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 74442
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 74443
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 74907
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 74908
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 75372
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 75373
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 75837
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 75838
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 76302
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 76303
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 76767
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 76768
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 77232
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 77233
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 77697
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 77698
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 78162
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 78163
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 78627
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 78628
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 79092
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 79093
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 79557
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 79558
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80022
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80023
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80487
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80488
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80952
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 80953
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 81417
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 81418
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 81882
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 81883
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 82347
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 82348
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 82812
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 82813
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 83277
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 83278
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 83742
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 83743
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 84207
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 84208
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 84672
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 84673
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 85137
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 85138
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 85602
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 85603
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86067
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86068
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86532
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86533
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86997
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 86998
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 87462
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 87463
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 87927
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 87928
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 88392
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 88393
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 88857
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 88858
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 89322
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 89323
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 89787
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 89788
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 90252
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 90253
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 90717
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 90718
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 91182
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 91183
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 91647
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 91648
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 92112
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 92113
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 92577
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 92578
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93042
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93043
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93507
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93508
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93972
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 93973
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 94437
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 94438
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 94902
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 94903
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 95367
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 95368
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 95832
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 95833
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 96297
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 96298
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 96762
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 96763
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 97227
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 97228
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 97692
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 97693
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 98157
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 98158
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 98622
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 98623
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 99087
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 99088
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 99552
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 99553
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100017
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100018
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100482
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100483
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100947
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 100948
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 101412
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 101413
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 101877
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 101878
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 102342
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 102343
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 102807
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 102808
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 103272
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 103273
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 103737
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 103738
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 104202
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 104203
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 104667
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 104668
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 105132
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 105133
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 105597
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 105598
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106062
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106063
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106527
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106528
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106992
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 106993
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 107457
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 107458
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 107922
/home/u17/jiachuanxu/CosmoLike/KL_WFIRST/./compute_covariances_fourier 107923
